### PR TITLE
npc:custom/pvpwarperupdated and working

### PR DESCRIPTION
**Pull request by paulraii**

### CODE REVIEW

**Comment by hurtsky** [comment]
the currently one not working? @paulraii

**Comment by paulraii** [comment]
the ranking and the people inside the room are not visible. always 0/10 even we are almost 4-5 in the pvp room.. the ranking also is not available. kills, deaths, sprees are not available.

**Comment by hurtsky** [comment]
alright will test it

**Comment by hurtsky** [comment]
@paulraii full of errors and warning.. please test it locally first... close pull request and please open new one with tested script.. thank you

**Pull request closed without merging**
